import { createSlice } from '@reduxjs/toolkit';

const cartSlice = createSlice({
  name: 'cart',
  initialState: [], // Initial state is an empty array representing the cart items
  reducers: {
    // Adds a product to the cart or increments quantity if it already exists
    addToCart: (state, action) => {
      const item = action.payload;

      // Check if the item already exists in the cart by matching the id
      const existingItem = state.find(p => p.id === item.id);

      if (existingItem) {
        // If item exists, increase its quantity by 1
        existingItem.quantity += 1;
      } else {
        // If item does not exist, add it with initial quantity of 1
        state.push({ ...item, quantity: 1 });
      }
    },

    // Removes an item from the cart by filtering out the item with the matching id
    removeFromCart: (state, action) => {
      // action.payload contains the id of the item to remove
      return state.filter(item => item.id !== action.payload);
    },

    // Updates the quantity of a specific item in the cart
    updateQuantity: (state, action) => {
      const { id, quantity } = action.payload;

      // Find the item in the cart by id
      const item = state.find(p => p.id === id);

      if (item) {
        // Update the quantity with the new value
        item.quantity = quantity;
      }
    },

    // Clears the entire cart by returning an empty array
    clearCart: () => {
      return [];
    },
  },
});

// Export the action creators generated by createSlice
export const { addToCart, removeFromCart, updateQuantity, clearCart } = cartSlice.actions;

// Export the reducer to be added in the store
export default cartSlice.reducer;
